version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - "./:/home"
      - "./0-create_database_if_missing.sql:/docker-entrypoint-initdb.d/0-create_database_if_missing.sql"
      - "./1-first_table.sql:/docker-entrypoint-initdb.d/1-first_table.sql"
      - "./2-list_values.sql:/docker-entrypoint-initdb.d/2-list_values.sql"
      - "./3-insert_value.sql:/docker-entrypoint-initdb.d/3-insert_value.sql"
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
      - "./temperatures.sql:/docker-entrypoint-initdb.d/temperatures.sql"
      - "./hbtn_0d_tvshows.sql:/docker-entrypoint-initdb.d/hbtn_0d_tvshows.sql"
      - "./hbtn_0d_tvshows_rate.sql:/docker-entrypoint-initdb.d/hbtn_0d_tvshows_rate.sql"

  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - "./:/home"
      - ./23-use_or_create_database:/docker-entrypoint-initdb.d/23-use_or_create_database:ro
      - ./24-insert:/docker-entrypoint-initdb.d/24-insert.js:ro
      - ./28-update:/docker-entrypoint-initdb.d/28-update.js:ro
      # - ./31-insert_school:/docker-entrypoint-initdb.d/31-insert_school:ro
      # - ./34-init:/docker-entrypoint-initdb.d/34-init:ro